Use block finalizaiton checker tool in docker tests
Signed-off-by: ghzlatarev <ghzlatarev@gmail.com>

diff --git a/.github/workflows/docker.yml b/.github/workflows/docker.yml
--- a/.github/workflows/docker.yml
+++ b/.github/workflows/docker.yml
@@ -51,31 +51,30 @@ jobs:
       -
         name: run docker image
         run: |
-          sudo docker run -d mantanetwork/${{ matrix.runtime.name }}:latest > docker_id.log
+          sudo docker run -p 9944:9944 -p 9945:9945 -d mantanetwork/${{ matrix.runtime.name }}:latest --unsafe-ws-external -- --unsafe-ws-external > docker_id.log
           sleep 30
       -
-        name: check syncing
+        name: Show log
         run: |
           echo "Get the docker container ID:"
           image_id=`cat docker_id.log`
           echo $image_id
           echo "Adjusting permissions so we can access docker logs..."
           sudo chmod -R +x /var/lib/docker/
-          sudo cat /var/lib/docker/containers/${image_id}/${image_id}-json.log > docker_output.log
-          cat docker_output.log
-          echo "Parsing the first best blocks emitted from the relaychain and parachain..."
-          grep 'best: #.*' docker_output.log | head -n 2 | while read -r line; do words=($line); echo ${words[9]:1} >> relay_output.txt; done
-          echo "Fail if there is no result..."
-          if [ ! -f relay_output.txt ]; then echo "No sync output detected"; exit 1; fi
-          cat relay_output.txt
-          echo "Fail if any one of the blocks is equal to zero or is not a number..."
-          nums=( $(cat relay_output.txt) )
-          if [ ${nums[0]} == 0 ]; then echo "Relay sync not detected. Best block is #0"; exit 1; fi
-          re1='^[0-9]+$'
-          if ! [[ ${nums[0]} =~ $re1 ]] ; then echo "Relay sync not detected. Best block is not a number."; exit 1; fi
-          if [ ${nums[1]} == 0 ]; then echo "Para sync not detected. Best block is #0."; exit 1; fi
-          re2='^[0-9]+$'
-          if ! [[ ${nums[1]} =~ $re2 ]] ; then echo "Para sync not detected. Best block is not a number."; exit 1; fi
-          echo "All good!"
+          sudo cat /var/lib/docker/containers/${image_id}/${image_id}-json.log
+      -
+        uses: actions/checkout@v2
+        with:
+          repository: Manta-Network/Dev-Tools
+          path: dev-tools
+      -
+        name: check if target block is finalized
+        run: |
+          cd dev-tools/check-finalized-block
+          yarn install
+          yarn
+          node index.js --para_address=ws://127.0.0.1:9944 --relay_address=ws://127.0.0.1:9945 --target_block=6
+          echo $?
+          if [ $? == 1 ]; then echo "Failed to finalize the target block - 6"; exit 1; fi
 
 # yamllint enable rule:line-length
