Docker image integration test

diff --git a/.github/workflows/docker.yml b/.github/workflows/docker.yml
--- a/.github/workflows/docker.yml
+++ b/.github/workflows/docker.yml
@@ -26,3 +26,31 @@ jobs:
             mantanetwork/calamari:${{ github.event.release.tag_name }}
           build-args: |
             PARA_BINARY_REF=${{ github.event.release.tag_name }}
+
+  check-docker-hub-deploy:
+    needs: docker-hub-deploy
+    runs-on: ubuntu-20.04
+    steps:
+      -
+        name: run docker image
+        run: |
+          sudo docker run -d mantanetwork/calamari:latest > docker_id.log
+      -
+        name: check syncing
+        run: |
+          echo "Get the docker container ID:"
+          image_id=`cat docker_id.log`
+          echo $image_id
+          echo "Adjusting permissions so we can access docker logs..."
+          sudo chmod -R +x /var/lib/docker/
+          sudo cat /var/lib/docker/containers/${image_id}/${image_id}-json.log > docker_output.log
+          echo "Parsing the first best blocks emitted from the relaychain and parachain..."
+          grep 'best: #.*' docker_output.log | head -n 2 | while read -r line; do words=($line); echo ${words[9]:1} >> relay_output.txt; done
+          echo "Fail if there is no result..."
+          if [ ! -f relay_output.txt ]; then echo "sync not detected"; exit 1; fi
+          cat relay_output.txt
+          echo "Fail if any one of the blocks is equal to zero..."
+          nums=( $(cat relay_output.txt) )
+          if [ ${nums[0]} == 0 ]; then echo "sync not detected"; exit 1; fi
+          if [ ${nums[1]} == 0 ]; then echo "sync not detected"; exit 1; fi
+          echo "All good!"
