Add manta parchain docker push and test jobs

diff --git a/.github/workflows/docker.yml b/.github/workflows/docker.yml
--- a/.github/workflows/docker.yml
+++ b/.github/workflows/docker.yml
@@ -11,6 +11,13 @@ on:
 jobs:
   docker-hub-deploy:
     runs-on: ubuntu-20.04
+    strategy:
+      matrix:
+        runtime:
+          -
+            name: calamari
+          -
+            name: manta
     steps:
       -
         uses: docker/setup-buildx-action@v1
@@ -23,21 +30,28 @@ jobs:
         uses: docker/build-push-action@v2
         with:
           push: true
-          file: docker/calamari.Dockerfile
+          file: docker/${{ matrix.runtime.name }}.Dockerfile
           tags: |
-            mantanetwork/calamari:latest
-            mantanetwork/calamari:${{ github.event.release.tag_name }}
+            mantanetwork/${{ matrix.runtime.name }}:latest
+            mantanetwork/${{ matrix.runtime.name }}:${{ github.event.release.tag_name }}
           build-args: |
             PARA_BINARY_REF=${{ github.event.release.tag_name }}
 
   check-docker-hub-deploy:
     needs: docker-hub-deploy
     runs-on: ubuntu-20.04
+    strategy:
+      matrix:
+        runtime:
+          -
+            name: calamari
+          # -
+          #   name: manta
     steps:
       -
         name: run docker image
         run: |
-          sudo docker run -d mantanetwork/calamari:latest > docker_id.log
+          sudo docker run -d mantanetwork/${{ matrix.runtime.name }}:latest > docker_id.log
       -
         name: check syncing
         run: |
@@ -47,15 +61,20 @@ jobs:
           echo "Adjusting permissions so we can access docker logs..."
           sudo chmod -R +x /var/lib/docker/
           sudo cat /var/lib/docker/containers/${image_id}/${image_id}-json.log > docker_output.log
+          cat docker_output.log
           echo "Parsing the first best blocks emitted from the relaychain and parachain..."
           grep 'best: #.*' docker_output.log | head -n 2 | while read -r line; do words=($line); echo ${words[9]:1} >> relay_output.txt; done
           echo "Fail if there is no result..."
-          if [ ! -f relay_output.txt ]; then echo "sync not detected"; exit 1; fi
+          if [ ! -f relay_output.txt ]; then echo "No sync output detected"; exit 1; fi
           cat relay_output.txt
-          echo "Fail if any one of the blocks is equal to zero..."
+          echo "Fail if any one of the blocks is equal to zero or is not a number..."
           nums=( $(cat relay_output.txt) )
-          if [ ${nums[0]} == 0 ]; then echo "sync not detected"; exit 1; fi
-          if [ ${nums[1]} == 0 ]; then echo "sync not detected"; exit 1; fi
+          if [ ${nums[0]} == 0 ]; then echo "Relay sync not detected. Best block is #0"; exit 1; fi
+          re1='^[0-9]+$'
+          if ! [[ ${nums[0]} =~ $re1 ]] ; then echo "Relay sync not detected. Best block is not a number."; exit 1; fi
+          if [ ${nums[1]} == 0 ]; then echo "Para sync not detected. Best block is #0."; exit 1; fi
+          re2='^[0-9]+$'
+          if ! [[ ${nums[1]} =~ $re2 ]] ; then echo "Para sync not detected. Best block is not a number."; exit 1; fi
           echo "All good!"
 
 # yamllint enable rule:line-length
diff --git a/.github/workflows/publish-draft-releases.yml b/.github/workflows/publish-draft-releases.yml
--- a/.github/workflows/publish-draft-releases.yml
+++ b/.github/workflows/publish-draft-releases.yml
@@ -1199,6 +1199,13 @@ jobs:
       - build-node-current
       - start-docker-image-tester
     runs-on: ubuntu-20.04
+    strategy:
+      matrix:
+        runtime:
+          -
+            name: calamari
+          # -
+          #   name: manta
     steps:
       -
         uses: actions/checkout@v2
@@ -1215,15 +1222,15 @@ jobs:
           chmod +x manta
           GIT_TAG=${{ github.event.release.tag_name }}
           BINARY_NAME=manta
-          ln -s calamari.Dockerfile Dockerfile
+          ln -s ${{ matrix.runtime.name }}.Dockerfile Dockerfile
           docker build \
             --build-arg PARA_BINARY_REF=${GIT_TAG} \
             --build-arg PARA_BINARY_URL=manta \
-            --tag calamari   ./
+            --tag ${{ matrix.runtime.name }}   ./
       -
         name: run docker image
         run: |
-          sudo docker run -d calamari > docker_id.log
+          sudo docker run -d ${{ matrix.runtime.name }} > docker_id.log
       -
         name: check syncing
         run: |
@@ -1233,15 +1240,20 @@ jobs:
           echo "Adjusting permissions so we can access docker logs..."
           sudo chmod -R +x /var/lib/docker/
           sudo cat /var/lib/docker/containers/${image_id}/${image_id}-json.log > docker_output.log
+          cat docker_output.log
           echo "Parsing the first best blocks emitted from the relaychain and parachain..."
           grep 'best: #.*' docker_output.log | head -n 2 | while read -r line; do words=($line); echo ${words[9]:1} >> relay_output.txt; done
           echo "Fail if there is no result..."
-          if [ ! -f relay_output.txt ]; then echo "sync not detected"; exit 1; fi
+          if [ ! -f relay_output.txt ]; then echo "No sync output detected"; exit 1; fi
           cat relay_output.txt
-          echo "Fail if any one of the blocks is equal to zero..."
+          echo "Fail if any one of the blocks is equal to zero or is not a number..."
           nums=( $(cat relay_output.txt) )
-          if [ ${nums[0]} == 0 ]; then echo "sync not detected"; exit 1; fi
-          if [ ${nums[1]} == 0 ]; then echo "sync not detected"; exit 1; fi
+          if [ ${nums[0]} == 0 ]; then echo "Relay sync not detected. Best block is #0"; exit 1; fi
+          re1='^[0-9]+$'
+          if ! [[ ${nums[0]} =~ $re1 ]] ; then echo "Relay sync not detected. Best block is not a number."; exit 1; fi
+          if [ ${nums[1]} == 0 ]; then echo "Para sync not detected. Best block is #0."; exit 1; fi
+          re2='^[0-9]+$'
+          if ! [[ ${nums[1]} =~ $re2 ]] ; then echo "Para sync not detected. Best block is not a number."; exit 1; fi
           echo "All good!"
 
   stop-docker-image-tester:
