Trigger
Signed-off-by: Georgi Zlatarev <georgi.zlatarev@manta.network>

diff --git a/.github/workflows/integration_test_dolphin.yml b/.github/workflows/integration_test_dolphin.yml
--- a/.github/workflows/integration_test_dolphin.yml
+++ b/.github/workflows/integration_test_dolphin.yml
@@ -271,11 +271,13 @@ jobs:
             --address=ws://127.0.0.1:9921
       - name: run test suites
         run: |
-          # TODO: implement moonbeam-like js test suite triggers here
           sleep 120
           cd ${{ github.workspace }}/Manta/tests
           yarn install
           yarn
+          yarn stress_benchmark_test --address=ws://127.0.0.1:9921 --exit
+          echo $?
+          if [ $? != 0 ]; then echo "Stress benchmark test failed!"; exit 1; fi
           yarn correctness_test --address=ws://127.0.0.1:9921 --exit
           echo $?
           if [ $? != 0 ]; then echo "Ledger RPC correctness test failed!"; exit 1; fi
