Check
Signed-off-by: Georgi Zlatarev <georgi.zlatarev@manta.network>

diff --git a/.github/workflows/integration_test_calamari.yml b/.github/workflows/integration_test_calamari.yml
--- a/.github/workflows/integration_test_calamari.yml
+++ b/.github/workflows/integration_test_calamari.yml
@@ -34,81 +34,81 @@ jobs:
         run: |
           echo "::set-output name=stable::$(rustc +stable --version)"
           echo "::set-output name=nightly::$(rustc +nightly --version)"
-  build-node-current:
-    if: contains(github.event.pull_request.labels.*.name, 'A-calamari' || github.ref == 'refs/heads/manta')
-    needs: start-node-builder-current
-    runs-on: ${{ needs.start-node-builder-current.outputs.runner-label }}
-    env:
-      CARGO_TERM_COLOR: always
-    steps:
-      - uses: actions/checkout@v2
-      - name: install sccache
-        env:
-          SCCACHE_RELEASE_URL: https://github.com/mozilla/sccache/releases/download
-          SCCACHE_VERSION: v0.2.15
-        run: |
-          SCCACHE_FILE=sccache-$SCCACHE_VERSION-x86_64-unknown-linux-musl
-          mkdir -p $HOME/.local/bin
-          curl -L "$SCCACHE_RELEASE_URL/$SCCACHE_VERSION/$SCCACHE_FILE.tar.gz" | tar xz
-          mv -f $SCCACHE_FILE/sccache $HOME/.local/bin/sccache
-          chmod +x $HOME/.local/bin/sccache
-          echo "$HOME/.local/bin" >> $GITHUB_PATH
-          echo "$HOME/.cargo/bin" >> $GITHUB_PATH
-      - name: cache cargo registry
-        uses: actions/cache@v2
-        with:
-          path: |
-            ~/.cargo/registry
-            ~/.cargo/git
-          key: cargo-${{ hashFiles('**/Cargo.lock') }}
-          restore-keys: |
-            cargo-
-      - name: cache sccache
-        uses: actions/cache@v2
-        continue-on-error: false
-        with:
-          path: /home/runner/.cache/sccache
-          key: sccache-${{ hashFiles('**/Cargo.lock') }}
-          restore-keys: |
-            sccache-
-      - name: start sccache server
-        run: sccache --start-server
-      - name: init
-        run: |
-          sudo apt update
-          sudo apt install -y pkg-config libssl-dev
-          curl -s https://sh.rustup.rs -sSf | sh -s -- -y
-          source ${HOME}/.cargo/env
-          rustup toolchain install stable
-          rustup default stable
-          rustup update
-          rustup target add wasm32-unknown-unknown
-      - name: build
-        env:
-          RUST_BACKTRACE: full
-          RUSTC_WRAPPER: sccache
-          SCCACHE_CACHE_SIZE: 2G
-          SCCACHE_DIR: /home/runner/.cache/sccache
-        run: |
-          source ${HOME}/.cargo/env
-          RUSTC_BOOTSTRAP=1 cargo build --profile production --verbose
-      - name: stop sccache server
-        run: sccache --stop-server || true
-      - if: always()
-        name: upload
-        uses: actions/upload-artifact@v2
-        with:
-          name: manta
-          path: target/production/manta
-      - if: always()
-        name: upload
-        uses: actions/upload-artifact@v2
-        with:
-          name: config-for-integration-test
-          path: .github/resources/config-for-integration-test.json
+  # build-node-current:
+  #   if: contains(github.event.pull_request.labels.*.name, 'A-calamari' || github.ref == 'refs/heads/manta')
+  #   needs: start-node-builder-current
+  #   runs-on: ${{ needs.start-node-builder-current.outputs.runner-label }}
+  #   env:
+  #     CARGO_TERM_COLOR: always
+  #   steps:
+  #     - uses: actions/checkout@v2
+  #     - name: install sccache
+  #       env:
+  #         SCCACHE_RELEASE_URL: https://github.com/mozilla/sccache/releases/download
+  #         SCCACHE_VERSION: v0.2.15
+  #       run: |
+  #         SCCACHE_FILE=sccache-$SCCACHE_VERSION-x86_64-unknown-linux-musl
+  #         mkdir -p $HOME/.local/bin
+  #         curl -L "$SCCACHE_RELEASE_URL/$SCCACHE_VERSION/$SCCACHE_FILE.tar.gz" | tar xz
+  #         mv -f $SCCACHE_FILE/sccache $HOME/.local/bin/sccache
+  #         chmod +x $HOME/.local/bin/sccache
+  #         echo "$HOME/.local/bin" >> $GITHUB_PATH
+  #         echo "$HOME/.cargo/bin" >> $GITHUB_PATH
+  #     - name: cache cargo registry
+  #       uses: actions/cache@v2
+  #       with:
+  #         path: |
+  #           ~/.cargo/registry
+  #           ~/.cargo/git
+  #         key: cargo-${{ hashFiles('**/Cargo.lock') }}
+  #         restore-keys: |
+  #           cargo-
+  #     - name: cache sccache
+  #       uses: actions/cache@v2
+  #       continue-on-error: false
+  #       with:
+  #         path: /home/runner/.cache/sccache
+  #         key: sccache-${{ hashFiles('**/Cargo.lock') }}
+  #         restore-keys: |
+  #           sccache-
+  #     - name: start sccache server
+  #       run: sccache --start-server
+  #     - name: init
+  #       run: |
+  #         sudo apt update
+  #         sudo apt install -y pkg-config libssl-dev
+  #         curl -s https://sh.rustup.rs -sSf | sh -s -- -y
+  #         source ${HOME}/.cargo/env
+  #         rustup toolchain install stable
+  #         rustup default stable
+  #         rustup update
+  #         rustup target add wasm32-unknown-unknown
+  #     - name: build
+  #       env:
+  #         RUST_BACKTRACE: full
+  #         RUSTC_WRAPPER: sccache
+  #         SCCACHE_CACHE_SIZE: 2G
+  #         SCCACHE_DIR: /home/runner/.cache/sccache
+  #       run: |
+  #         source ${HOME}/.cargo/env
+  #         RUSTC_BOOTSTRAP=1 cargo build --profile production --verbose
+  #     - name: stop sccache server
+  #       run: sccache --stop-server || true
+  #     - if: always()
+  #       name: upload
+  #       uses: actions/upload-artifact@v2
+  #       with:
+  #         name: manta
+  #         path: target/production/manta
+  #     - if: always()
+  #       name: upload
+  #       uses: actions/upload-artifact@v2
+  #       with:
+  #         name: config-for-integration-test
+  #         path: .github/resources/config-for-integration-test.json
   calamari-integration-test:
     if: contains(github.event.pull_request.labels.*.name, 'A-calamari' || github.ref == 'refs/heads/manta')
-    needs: [build-node-current, start-calamari-integration-tester]
+    needs: [start-calamari-integration-tester]
     runs-on: ${{ needs.start-calamari-integration-tester.outputs.runner-label }}
     timeout-minutes: 90
     strategy:
@@ -137,12 +137,13 @@ jobs:
           mkdir -p $HOME/.local/bin
           echo "${HOME}/.nvm/versions/node/v16.3.0/bin" >> $GITHUB_PATH
           echo "${HOME}/.local/bin" >> $GITHUB_PATH
-      - name: fetch manta
-        uses: actions/download-artifact@v2
-        with:
-          name: manta
+      # - name: fetch manta
+      #   uses: actions/download-artifact@v2
+      #   with:
+      #     name: manta
       - name: mv and chmod manta
         run: |
+          wget https://github.com/Manta-Network/Manta/releases/download/v4.0.0-alpha.1/manta
           mv ${{ github.workspace }}/manta $HOME/.local/bin/
           chmod +x $HOME/.local/bin/manta
           ls -ahl ${{ github.workspace }}/
@@ -169,14 +170,13 @@ jobs:
           ls -ahl $HOME/.local/share/calamari-pc/
           echo "::set-output name=short-sha::${GITHUB_SHA:0:7}"
           manta export-state --chain $HOME/.local/share/calamari-pc/${{ matrix.chain-spec.id }}-${GITHUB_SHA:0:7}-spec.json > $HOME/.local/share/calamari-pc/${{ matrix.chain-spec.id }}-state.json || true
-      - name: Install git lfs
-        run: |
-          sudo apt-get update && apt-get install git-lfs
       - uses: actions/checkout@v2
         with:
           repository: Manta-Network/Manta
           path: Manta
           lfs: true
+      - name: Checkout LFS objects
+        run: git lfs checkout
       - name: inject manta-pay storage
         run: |
           mv $HOME/.local/share/calamari-pc/${{ matrix.chain-spec.id }}-${GITHUB_SHA:0:7}-spec.json ${{ github.workspace }}/Manta/tests/fork.json
@@ -390,56 +390,56 @@ jobs:
         name: test - calamari alice peered successfully
         run: |
           grep '\[Parachain\] 💤 Idle (${{ matrix.chain-spec.expected.peer-count.para }} peers)' ${{ github.workspace }}/polkadot-launch/9921.log
-  docker-image-test:
-    if: contains(github.event.pull_request.labels.*.name, 'A-calamari' || github.ref == 'refs/heads/manta')
-    needs: [build-node-current, start-docker-image-tester]
-    runs-on: ubuntu-20.04
-    strategy:
-      matrix:
-        runtime:
-          - name: calamari
-    steps:
-      - uses: actions/checkout@v2
-      - name: fetch manta
-        uses: actions/download-artifact@v2
-        with:
-          name: manta
-      - name: build docker image
-        run: |
-          mv manta docker/manta
-          cd docker/
-          chmod +x manta
-          GIT_TAG=${{ github.event.release.tag_name }}
-          BINARY_NAME=manta
-          ln -s ${{ matrix.runtime.name }}.Dockerfile Dockerfile
-          docker build \
-            --build-arg PARA_BINARY_REF=${GIT_TAG} \
-            --build-arg PARA_BINARY_URL=manta \
-            --tag ${{ matrix.runtime.name }}   ./
-      - name: run docker image
-        run: |
-          sudo docker run -p 9944:9944 -p 9945:9945 -d ${{ matrix.runtime.name }} --unsafe-ws-external -- --unsafe-ws-external > docker_id.log
-          sleep 60
-      - name: Show log
-        run: |
-          echo "Get the docker container ID:"
-          image_id=`cat docker_id.log`
-          echo $image_id
-          echo "Adjusting permissions so we can access docker logs..."
-          sudo chmod -R +x /var/lib/docker/
-          sudo cat /var/lib/docker/containers/${image_id}/${image_id}-json.log
-      - uses: actions/checkout@v2
-        with:
-          repository: Manta-Network/Dev-Tools
-          path: dev-tools
-      - name: check if target block is finalized
-        run: |
-          cd dev-tools/check-finalized-block
-          yarn install
-          yarn
-          node index.js --para_address=ws://127.0.0.1:9944 --relay_address=ws://127.0.0.1:9945 --target_block=6
-          echo $?
-          if [ $? == 1 ]; then echo "Failed to finalize the target block - 6"; exit 1; fi
+  # docker-image-test:
+  #   if: contains(github.event.pull_request.labels.*.name, 'A-calamari' || github.ref == 'refs/heads/manta')
+  #   needs: [start-docker-image-tester]
+  #   runs-on: ubuntu-20.04
+  #   strategy:
+  #     matrix:
+  #       runtime:
+  #         - name: calamari
+  #   steps:
+  #     - uses: actions/checkout@v2
+  #     - name: fetch manta
+  #       uses: actions/download-artifact@v2
+  #       with:
+  #         name: manta
+  #     - name: build docker image
+  #       run: |
+  #         mv manta docker/manta
+  #         cd docker/
+  #         chmod +x manta
+  #         GIT_TAG=${{ github.event.release.tag_name }}
+  #         BINARY_NAME=manta
+  #         ln -s ${{ matrix.runtime.name }}.Dockerfile Dockerfile
+  #         docker build \
+  #           --build-arg PARA_BINARY_REF=${GIT_TAG} \
+  #           --build-arg PARA_BINARY_URL=manta \
+  #           --tag ${{ matrix.runtime.name }}   ./
+  #     - name: run docker image
+  #       run: |
+  #         sudo docker run -p 9944:9944 -p 9945:9945 -d ${{ matrix.runtime.name }} --unsafe-ws-external -- --unsafe-ws-external > docker_id.log
+  #         sleep 60
+  #     - name: Show log
+  #       run: |
+  #         echo "Get the docker container ID:"
+  #         image_id=`cat docker_id.log`
+  #         echo $image_id
+  #         echo "Adjusting permissions so we can access docker logs..."
+  #         sudo chmod -R +x /var/lib/docker/
+  #         sudo cat /var/lib/docker/containers/${image_id}/${image_id}-json.log
+  #     - uses: actions/checkout@v2
+  #       with:
+  #         repository: Manta-Network/Dev-Tools
+  #         path: dev-tools
+  #     - name: check if target block is finalized
+  #       run: |
+  #         cd dev-tools/check-finalized-block
+  #         yarn install
+  #         yarn
+  #         node index.js --para_address=ws://127.0.0.1:9944 --relay_address=ws://127.0.0.1:9945 --target_block=6
+  #         echo $?
+  #         if [ $? == 1 ]; then echo "Failed to finalize the target block - 6"; exit 1; fi
   # HELPER JOBS BELOW
   start-node-builder-current:
     if: contains(github.event.pull_request.labels.*.name, 'A-calamari' || github.ref == 'refs/heads/manta')
@@ -464,23 +464,23 @@ jobs:
           aws-instance-root-volume-size: 32
           aws-image-search-pattern: ${{ env.AWS_IMAGE_SEARCH_PATTERN }}
           aws-image-search-owners: ${{ env.AWS_IMAGE_SEARCH_OWNERS }}
-  stop-node-builder-current:
-    if: ${{ always() }}
-    needs: [start-node-builder-current, build-node-current]
-    runs-on: ubuntu-20.04
-    steps:
-      - continue-on-error: true
-        uses: audacious-network/aws-github-runner@v1.0.33
-        with:
-          mode: stop
-          github-token: ${{ secrets.SELF_HOSTED_RUNNER_TOKEN }}
-          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
-          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
-          aws-region: ${{ needs.start-node-builder-current.outputs.aws-region }}
-          runner-label: ${{ needs.start-node-builder-current.outputs.runner-label }}
-          aws-instance-id: ${{ needs.start-node-builder-current.outputs.aws-instance-id }}
-      - name: discard stopper success/failure
-        run: true
+  # stop-node-builder-current:
+  #   if: ${{ always() }}
+  #   needs: [start-node-builder-current, build-node-current]
+  #   runs-on: ubuntu-20.04
+  #   steps:
+  #     - continue-on-error: true
+  #       uses: audacious-network/aws-github-runner@v1.0.33
+  #       with:
+  #         mode: stop
+  #         github-token: ${{ secrets.SELF_HOSTED_RUNNER_TOKEN }}
+  #         aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
+  #         aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
+  #         aws-region: ${{ needs.start-node-builder-current.outputs.aws-region }}
+  #         runner-label: ${{ needs.start-node-builder-current.outputs.runner-label }}
+  #         aws-instance-id: ${{ needs.start-node-builder-current.outputs.aws-instance-id }}
+  #     - name: discard stopper success/failure
+  #       run: true
   start-calamari-integration-tester:
     if: contains(github.event.pull_request.labels.*.name, 'A-calamari' || github.ref == 'refs/heads/manta')
     runs-on: ubuntu-20.04
diff --git a/.github/workflows/integration_test_dolphin.yml b/.github/workflows/integration_test_dolphin.yml
--- a/.github/workflows/integration_test_dolphin.yml
+++ b/.github/workflows/integration_test_dolphin.yml
@@ -34,81 +34,81 @@ jobs:
         run: |
           echo "::set-output name=stable::$(rustc +stable --version)"
           echo "::set-output name=nightly::$(rustc +nightly --version)"
-  build-node-current:
-    if: contains(github.event.pull_request.labels.*.name, 'A-dolphin' || github.ref == 'refs/heads/manta')
-    needs: start-node-builder-current
-    runs-on: ${{ needs.start-node-builder-current.outputs.runner-label }}
-    env:
-      CARGO_TERM_COLOR: always
-    steps:
-      - uses: actions/checkout@v2
-      - name: install sccache
-        env:
-          SCCACHE_RELEASE_URL: https://github.com/mozilla/sccache/releases/download
-          SCCACHE_VERSION: v0.2.15
-        run: |
-          SCCACHE_FILE=sccache-$SCCACHE_VERSION-x86_64-unknown-linux-musl
-          mkdir -p $HOME/.local/bin
-          curl -L "$SCCACHE_RELEASE_URL/$SCCACHE_VERSION/$SCCACHE_FILE.tar.gz" | tar xz
-          mv -f $SCCACHE_FILE/sccache $HOME/.local/bin/sccache
-          chmod +x $HOME/.local/bin/sccache
-          echo "$HOME/.local/bin" >> $GITHUB_PATH
-          echo "$HOME/.cargo/bin" >> $GITHUB_PATH
-      - name: cache cargo registry
-        uses: actions/cache@v2
-        with:
-          path: |
-            ~/.cargo/registry
-            ~/.cargo/git
-          key: cargo-${{ hashFiles('**/Cargo.lock') }}
-          restore-keys: |
-            cargo-
-      - name: cache sccache
-        uses: actions/cache@v2
-        continue-on-error: false
-        with:
-          path: /home/runner/.cache/sccache
-          key: sccache-${{ hashFiles('**/Cargo.lock') }}
-          restore-keys: |
-            sccache-
-      - name: start sccache server
-        run: sccache --start-server
-      - name: init
-        run: |
-          sudo apt update
-          sudo apt install -y pkg-config libssl-dev
-          curl -s https://sh.rustup.rs -sSf | sh -s -- -y
-          source ${HOME}/.cargo/env
-          rustup toolchain install stable
-          rustup default stable
-          rustup update
-          rustup target add wasm32-unknown-unknown
-      - name: build
-        env:
-          RUST_BACKTRACE: full
-          RUSTC_WRAPPER: sccache
-          SCCACHE_CACHE_SIZE: 2G
-          SCCACHE_DIR: /home/runner/.cache/sccache
-        run: |
-          source ${HOME}/.cargo/env
-          RUSTC_BOOTSTRAP=1 cargo build --profile production --verbose
-      - name: stop sccache server
-        run: sccache --stop-server || true
-      - if: always()
-        name: upload
-        uses: actions/upload-artifact@v2
-        with:
-          name: manta
-          path: target/production/manta
-      - if: always()
-        name: upload
-        uses: actions/upload-artifact@v2
-        with:
-          name: config-for-integration-test
-          path: .github/resources/config-for-integration-test.json
+  # build-node-current:
+  #   if: contains(github.event.pull_request.labels.*.name, 'A-dolphin' || github.ref == 'refs/heads/manta')
+  #   needs: start-node-builder-current
+  #   runs-on: ${{ needs.start-node-builder-current.outputs.runner-label }}
+  #   env:
+  #     CARGO_TERM_COLOR: always
+  #   steps:
+  #     - uses: actions/checkout@v2
+  #     - name: install sccache
+  #       env:
+  #         SCCACHE_RELEASE_URL: https://github.com/mozilla/sccache/releases/download
+  #         SCCACHE_VERSION: v0.2.15
+  #       run: |
+  #         SCCACHE_FILE=sccache-$SCCACHE_VERSION-x86_64-unknown-linux-musl
+  #         mkdir -p $HOME/.local/bin
+  #         curl -L "$SCCACHE_RELEASE_URL/$SCCACHE_VERSION/$SCCACHE_FILE.tar.gz" | tar xz
+  #         mv -f $SCCACHE_FILE/sccache $HOME/.local/bin/sccache
+  #         chmod +x $HOME/.local/bin/sccache
+  #         echo "$HOME/.local/bin" >> $GITHUB_PATH
+  #         echo "$HOME/.cargo/bin" >> $GITHUB_PATH
+  #     - name: cache cargo registry
+  #       uses: actions/cache@v2
+  #       with:
+  #         path: |
+  #           ~/.cargo/registry
+  #           ~/.cargo/git
+  #         key: cargo-${{ hashFiles('**/Cargo.lock') }}
+  #         restore-keys: |
+  #           cargo-
+  #     - name: cache sccache
+  #       uses: actions/cache@v2
+  #       continue-on-error: false
+  #       with:
+  #         path: /home/runner/.cache/sccache
+  #         key: sccache-${{ hashFiles('**/Cargo.lock') }}
+  #         restore-keys: |
+  #           sccache-
+  #     - name: start sccache server
+  #       run: sccache --start-server
+  #     - name: init
+  #       run: |
+  #         sudo apt update
+  #         sudo apt install -y pkg-config libssl-dev
+  #         curl -s https://sh.rustup.rs -sSf | sh -s -- -y
+  #         source ${HOME}/.cargo/env
+  #         rustup toolchain install stable
+  #         rustup default stable
+  #         rustup update
+  #         rustup target add wasm32-unknown-unknown
+  #     - name: build
+  #       env:
+  #         RUST_BACKTRACE: full
+  #         RUSTC_WRAPPER: sccache
+  #         SCCACHE_CACHE_SIZE: 2G
+  #         SCCACHE_DIR: /home/runner/.cache/sccache
+  #       run: |
+  #         source ${HOME}/.cargo/env
+  #         RUSTC_BOOTSTRAP=1 cargo build --profile production --verbose
+  #     - name: stop sccache server
+  #       run: sccache --stop-server || true
+  #     - if: always()
+  #       name: upload
+  #       uses: actions/upload-artifact@v2
+  #       with:
+  #         name: manta
+  #         path: target/production/manta
+  #     - if: always()
+  #       name: upload
+  #       uses: actions/upload-artifact@v2
+  #       with:
+  #         name: config-for-integration-test
+  #         path: .github/resources/config-for-integration-test.json
   dolphin-integration-test:
     if: contains(github.event.pull_request.labels.*.name, 'A-dolphin' || github.ref == 'refs/heads/manta')
-    needs: [build-node-current, start-dolphin-integration-tester]
+    needs: [start-dolphin-integration-tester]
     runs-on: ${{ needs.start-dolphin-integration-tester.outputs.runner-label }}
     timeout-minutes: 90
     strategy:
@@ -137,12 +137,13 @@ jobs:
           mkdir -p $HOME/.local/bin
           echo "${HOME}/.nvm/versions/node/v16.3.0/bin" >> $GITHUB_PATH
           echo "${HOME}/.local/bin" >> $GITHUB_PATH
-      - name: fetch manta
-        uses: actions/download-artifact@v2
-        with:
-          name: manta
+      # - name: fetch manta
+      #   uses: actions/download-artifact@v2
+      #   with:
+      #     name: manta
       - name: mv and chmod manta
         run: |
+          wget https://github.com/Manta-Network/Manta/releases/download/v4.0.0-alpha.1/manta
           mv ${{ github.workspace }}/manta $HOME/.local/bin/
           chmod +x $HOME/.local/bin/manta
           ls -ahl ${{ github.workspace }}/
@@ -169,14 +170,13 @@ jobs:
           ls -ahl $HOME/.local/share/calamari-pc/
           echo "::set-output name=short-sha::${GITHUB_SHA:0:7}"
           manta export-state --chain $HOME/.local/share/calamari-pc/${{ matrix.chain-spec.id }}-${GITHUB_SHA:0:7}-spec.json > $HOME/.local/share/calamari-pc/${{ matrix.chain-spec.id }}-state.json || true
-      - name: Install git lfs
-        run: |
-          sudo apt-get update && apt-get install git-lfs
       - uses: actions/checkout@v2
         with:
           repository: Manta-Network/Manta
           path: Manta
           lfs: true
+      - name: Checkout LFS objects
+        run: git lfs checkout
       - name: inject manta-pay storage
         run: |
           mv $HOME/.local/share/calamari-pc/${{ matrix.chain-spec.id }}-${GITHUB_SHA:0:7}-spec.json ${{ github.workspace }}/Manta/tests/fork.json
@@ -409,23 +409,23 @@ jobs:
           aws-instance-root-volume-size: 32
           aws-image-search-pattern: ${{ env.AWS_IMAGE_SEARCH_PATTERN }}
           aws-image-search-owners: ${{ env.AWS_IMAGE_SEARCH_OWNERS }}
-  stop-node-builder-current:
-    if: ${{ always() }}
-    needs: [start-node-builder-current, build-node-current]
-    runs-on: ubuntu-20.04
-    steps:
-      - continue-on-error: true
-        uses: audacious-network/aws-github-runner@v1.0.33
-        with:
-          mode: stop
-          github-token: ${{ secrets.SELF_HOSTED_RUNNER_TOKEN }}
-          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
-          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
-          aws-region: ${{ needs.start-node-builder-current.outputs.aws-region }}
-          runner-label: ${{ needs.start-node-builder-current.outputs.runner-label }}
-          aws-instance-id: ${{ needs.start-node-builder-current.outputs.aws-instance-id }}
-      - name: discard stopper success/failure
-        run: true
+  # stop-node-builder-current:
+  #   if: ${{ always() }}
+  #   needs: [start-node-builder-current, build-node-current]
+  #   runs-on: ubuntu-20.04
+  #   steps:
+  #     - continue-on-error: true
+  #       uses: audacious-network/aws-github-runner@v1.0.33
+  #       with:
+  #         mode: stop
+  #         github-token: ${{ secrets.SELF_HOSTED_RUNNER_TOKEN }}
+  #         aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
+  #         aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
+  #         aws-region: ${{ needs.start-node-builder-current.outputs.aws-region }}
+  #         runner-label: ${{ needs.start-node-builder-current.outputs.runner-label }}
+  #         aws-instance-id: ${{ needs.start-node-builder-current.outputs.aws-instance-id }}
+  #     - name: discard stopper success/failure
+  #       run: true
   start-dolphin-integration-tester:
     if: contains(github.event.pull_request.labels.*.name, 'A-dolphin' || github.ref == 'refs/heads/manta')
     runs-on: ubuntu-20.04
