Add pull-ledger-diff ci test for calamari (#919)
* Add pull-ledger-diff ci test for calamari

Signed-off-by: Georgi Zlatarev <georgi.zlatarev@manta.network>

* Add bigger sleep

Signed-off-by: Georgi Zlatarev <georgi.zlatarev@manta.network>

* Fix

Signed-off-by: Georgi Zlatarev <georgi.zlatarev@manta.network>

* Add governance to rpc performance test

Signed-off-by: Georgi Zlatarev <georgi.zlatarev@manta.network>

* Add governance to rpc performance test

Signed-off-by: Georgi Zlatarev <georgi.zlatarev@manta.network>

* Temp

Signed-off-by: Georgi Zlatarev <georgi.zlatarev@manta.network>

* Should work with governance. Needs cleanup

Signed-off-by: Georgi Zlatarev <georgi.zlatarev@manta.network>

* Wait less for finalizaiton

Signed-off-by: Georgi Zlatarev <georgi.zlatarev@manta.network>

* Clean up

Signed-off-by: Georgi Zlatarev <georgi.zlatarev@manta.network>

* Clean up

Signed-off-by: Georgi Zlatarev <georgi.zlatarev@manta.network>

* Add more sleep between governance executions

Signed-off-by: Georgi Zlatarev <georgi.zlatarev@manta.network>

* CLean up

Signed-off-by: Georgi Zlatarev <georgi.zlatarev@manta.network>

* Reduce expected avg sync time

Signed-off-by: Georgi Zlatarev <georgi.zlatarev@manta.network>

* Clean up

Signed-off-by: Georgi Zlatarev <georgi.zlatarev@manta.network>

* Clean up

Signed-off-by: Georgi Zlatarev <georgi.zlatarev@manta.network>

* Fix pass by reference

Signed-off-by: Georgi Zlatarev <georgi.zlatarev@manta.network>

Signed-off-by: Georgi Zlatarev <georgi.zlatarev@manta.network>
Signed-off-by: Charles Ferrell <charlie@manta.network>

diff --git a/.github/workflows/integration_test_calamari.yml b/.github/workflows/integration_test_calamari.yml
--- a/.github/workflows/integration_test_calamari.yml
+++ b/.github/workflows/integration_test_calamari.yml
@@ -255,10 +255,23 @@ jobs:
             --no-autorestart \
             -- \
             --address=ws://127.0.0.1:9921
+      - uses: actions/checkout@v2
+        with:
+          repository: Manta-Network/Manta
+          path: Manta
       - name: run test suites
         run: |
           # TODO: implement moonbeam-like js test suite triggers here
-          sleep 300
+          sleep 120
+          cd ${{ github.workspace }}/Manta/tests
+          yarn install
+          yarn
+          yarn correctness_test --address=ws://127.0.0.1:9921 --exit
+          echo $?
+          if [ $? != 0 ]; then echo "Ledger RPC correctness test failed!"; exit 1; fi
+          yarn performance_test --address=ws://127.0.0.1:9921 --exit
+          echo $?
+          if [ $? != 0 ]; then echo "Ledger RPC performance test failed!"; exit 1; fi
       - name: check if target block is finalized
         run: |
           cd ${{ github.workspace }}/dev-tools-calamari/check-finalized-block
