Simplify
Signed-off-by: Georgi Zlatarev <georgi.zlatarev@manta.network>

diff --git a/.github/workflows/integration_test_calamari.yml b/.github/workflows/integration_test_calamari.yml
--- a/.github/workflows/integration_test_calamari.yml
+++ b/.github/workflows/integration_test_calamari.yml
@@ -216,149 +216,149 @@ jobs:
         with:
           repository: Manta-Network/Dev-Tools
           path: dev-tools-calamari
-      - name: launch testnet
-        run: |
-          cd ${{ github.workspace }}/polkadot-launch
-          yarn install
-          yarn build
-          pm2 start dist/cli.js \
-            --name polkadot-launch \
-            --output ${{ github.workspace }}/polkadot-launch-for-${{ matrix.chain-spec.id }}-stdout.log \
-            --error ${{ github.workspace }}/polkadot-launch-for-${{ matrix.chain-spec.id }}-stderr.log \
-            --no-autorestart \
-            -- $HOME/.local/share/calamari-pc/${{ matrix.chain-spec.id }}-${GITHUB_SHA:0:7}-launch-config.json
-      - name: init measure-block-time rococo
-        run: |
-          cd ${{ github.workspace }}/dev-tools-rococo/measure-block-time
-          yarn install
-          pm2 start index.js \
-            --name measure-block-time-rococo-relay-for-${{ matrix.chain-spec.id }} \
-            --output ${{ github.workspace }}/measure-block-time-rococo-relay-for-${{ matrix.chain-spec.id }}-stdout.log \
-            --error ${{ github.workspace }}/measure-block-time-rococo-relay-for-${{ matrix.chain-spec.id }}-stderr.log \
-            --no-autorestart \
-            -- \
-            --address=ws://127.0.0.1:9911
-      - name: init measure-block-time calamari
-        run: |
-          cd ${{ github.workspace }}/dev-tools-calamari/measure-block-time
-          yarn install
-          pm2 start index.js \
-            --name measure-block-time-${{ matrix.chain-spec.id }} \
-            --output ${{ github.workspace }}/measure-block-time-${{ matrix.chain-spec.id }}-stdout.log \
-            --error ${{ github.workspace }}/measure-block-time-${{ matrix.chain-spec.id }}-stderr.log \
-            --no-autorestart \
-            -- \
-            --address=ws://127.0.0.1:9944
-      - uses: actions/checkout@v2
-        with:
-          repository: Manta-Network/Manta
-          path: Manta
-      - name: run test suites
-        run: |
-          sleep 120
-          cd ${{ github.workspace }}/Manta/tests
-          yarn install
-          yarn
-          yarn correctness_test --address=ws://127.0.0.1:9944 --exit
-          yarn performance_test --address=ws://127.0.0.1:9944 --exit
-      - name: check if target block is finalized
-        run: |
-          cd ${{ github.workspace }}/dev-tools-calamari/check-finalized-block
-          yarn install
-          yarn
-          node index.js --para_address=ws://127.0.0.1:9944 --relay_address=ws://127.0.0.1:9911 --target_block=${{ matrix.chain-spec.expected.block-count.para }}
-          if [ $? == 1 ]; then echo "Failed to finalize the target block - ${{ matrix.chain-spec.expected.block-count.para }}"; exit 1; fi
-      - name: stop testnet
-        run: |
-          cd ${{ github.workspace }}/polkadot-launch
-          pm2 stop measure-block-time-rococo-relay-for-${{ matrix.chain-spec.id }}
-          pm2 stop measure-block-time-${{ matrix.chain-spec.id }}
-          pm2 stop polkadot-launch
-      - if: always()
-        uses: actions/upload-artifact@v2
-        with:
-          name: polkadot-launch-for-${{ matrix.chain-spec.id }}-stdout.log
-          path: ${{ github.workspace }}/polkadot-launch-for-${{ matrix.chain-spec.id }}-stdout.log
-      - if: always()
-        uses: actions/upload-artifact@v2
-        with:
-          name: polkadot-launch-for-${{ matrix.chain-spec.id }}-stderr.log
-          path: ${{ github.workspace }}/polkadot-launch-for-${{ matrix.chain-spec.id }}-stderr.log
-      - if: always()
-        uses: actions/upload-artifact@v2
-        with:
-          name: measure-block-time-rococo-relay-for-${{ matrix.chain-spec.id }}-stdout.log
-          path: ${{ github.workspace }}/measure-block-time-rococo-relay-for-${{ matrix.chain-spec.id }}-stdout.log
-      - if: always()
-        uses: actions/upload-artifact@v2
-        with:
-          name: measure-block-time-rococo-relay-for-${{ matrix.chain-spec.id }}-stderr.log
-          path: ${{ github.workspace }}/measure-block-time-rococo-relay-for-${{ matrix.chain-spec.id }}-stderr.log
-      - if: always()
-        uses: actions/upload-artifact@v2
-        with:
-          name: measure-block-time-${{ matrix.chain-spec.id }}-stdout.log
-          path: ${{ github.workspace }}/measure-block-time-${{ matrix.chain-spec.id }}-stdout.log
-      - if: always()
-        uses: actions/upload-artifact@v2
-        with:
-          name: measure-block-time-${{ matrix.chain-spec.id }}-stderr.log
-          path: ${{ github.workspace }}/measure-block-time-${{ matrix.chain-spec.id }}-stderr.log
-      - if: always()
-        uses: actions/upload-artifact@v2
-        with:
-          name: rococo-alice-relay-for-${{ matrix.chain-spec.id }}.log
-          path: ${{ github.workspace }}/polkadot-launch/alice.log
-      - if: always()
-        uses: actions/upload-artifact@v2
-        with:
-          name: rococo-bob-relay-for-${{ matrix.chain-spec.id }}.log
-          path: ${{ github.workspace }}/polkadot-launch/bob.log
-      - if: always()
-        uses: actions/upload-artifact@v2
-        with:
-          name: ${{ matrix.chain-spec.id }}-alice.log
-          path: ${{ github.workspace }}/polkadot-launch/9944.log
-      - if: always()
-        uses: actions/upload-artifact@v2
-        with:
-          name: ${{ matrix.chain-spec.id }}-bob.log
-          path: ${{ github.workspace }}/polkadot-launch/9944.log
-      - name: parse rococo block times
-        run: |
-          grep '#.*' ${{ github.workspace }}/measure-block-time-rococo-relay-for-${{ matrix.chain-spec.id }}-stdout.log | while read -r line; do words=($line); echo ${words[6]},${words[10]} | tee ${{ github.workspace }}/block-time-rococo.csv; done
-          if [ ! -f ${{ github.workspace }}/block-time-rococo.csv ]; then echo "block times not detected"; exit 1; fi
-          jq -s -R '[split("\n") | .[] | select(length > 0) | split(",") | {block:.[0]|tonumber, time:.[1]|tonumber} ]' ${{ github.workspace }}/block-time-rococo.csv > ${{ github.workspace }}/block-time-rococo.json
-      - if: always()
-        uses: actions/upload-artifact@v2
-        with:
-          name: block-time-rococo-relay-for-${{ matrix.chain-spec.id }}.json
-          path: ${{ github.workspace }}/block-time-rococo.json
-      # - if: always()
-      # - name: parse calamari block times
+      # - name: launch testnet
       #   run: |
-      #     grep '#.*' ${{ github.workspace }}/measure-block-time-${{ matrix.chain-spec.id }}-stdout.log | while read -r line; do words=($line); echo ${words[6]},${words[10]} | tee ${{ github.workspace }}/block-time-${{ matrix.chain-spec.id }}.csv; done
-      #     if [ ! -f ${{ github.workspace }}/block-time-${{ matrix.chain-spec.id }}.csv ]; then echo "block times not detected"; exit 1; fi
-      #     jq -s -R '[split("\n") | .[] | select(length > 0) | split(",") | {block:.[0]|tonumber, time:.[1]|tonumber} ]' ${{ github.workspace }}/block-time-${{ matrix.chain-spec.id }}.csv > ${{ github.workspace }}/block-time-${{ matrix.chain-spec.id }}.json
+      #     cd ${{ github.workspace }}/polkadot-launch
+      #     yarn install
+      #     yarn build
+      #     pm2 start dist/cli.js \
+      #       --name polkadot-launch \
+      #       --output ${{ github.workspace }}/polkadot-launch-for-${{ matrix.chain-spec.id }}-stdout.log \
+      #       --error ${{ github.workspace }}/polkadot-launch-for-${{ matrix.chain-spec.id }}-stderr.log \
+      #       --no-autorestart \
+      #       -- $HOME/.local/share/calamari-pc/${{ matrix.chain-spec.id }}-${GITHUB_SHA:0:7}-launch-config.json
+      # - name: init measure-block-time rococo
+      #   run: |
+      #     cd ${{ github.workspace }}/dev-tools-rococo/measure-block-time
+      #     yarn install
+      #     pm2 start index.js \
+      #       --name measure-block-time-rococo-relay-for-${{ matrix.chain-spec.id }} \
+      #       --output ${{ github.workspace }}/measure-block-time-rococo-relay-for-${{ matrix.chain-spec.id }}-stdout.log \
+      #       --error ${{ github.workspace }}/measure-block-time-rococo-relay-for-${{ matrix.chain-spec.id }}-stderr.log \
+      #       --no-autorestart \
+      #       -- \
+      #       --address=ws://127.0.0.1:9911
+      # - name: init measure-block-time calamari
+      #   run: |
+      #     cd ${{ github.workspace }}/dev-tools-calamari/measure-block-time
+      #     yarn install
+      #     pm2 start index.js \
+      #       --name measure-block-time-${{ matrix.chain-spec.id }} \
+      #       --output ${{ github.workspace }}/measure-block-time-${{ matrix.chain-spec.id }}-stdout.log \
+      #       --error ${{ github.workspace }}/measure-block-time-${{ matrix.chain-spec.id }}-stderr.log \
+      #       --no-autorestart \
+      #       -- \
+      #       --address=ws://127.0.0.1:9944
+      # - uses: actions/checkout@v2
+      #   with:
+      #     repository: Manta-Network/Manta
+      #     path: Manta
+      # - name: run test suites
+      #   run: |
+      #     sleep 120
+      #     cd ${{ github.workspace }}/Manta/tests
+      #     yarn install
+      #     yarn
+      #     yarn correctness_test --address=ws://127.0.0.1:9944 --exit
+      #     yarn performance_test --address=ws://127.0.0.1:9944 --exit
+      # - name: check if target block is finalized
+      #   run: |
+      #     cd ${{ github.workspace }}/dev-tools-calamari/check-finalized-block
+      #     yarn install
+      #     yarn
+      #     node index.js --para_address=ws://127.0.0.1:9944 --relay_address=ws://127.0.0.1:9911 --target_block=${{ matrix.chain-spec.expected.block-count.para }}
+      #     if [ $? == 1 ]; then echo "Failed to finalize the target block - ${{ matrix.chain-spec.expected.block-count.para }}"; exit 1; fi
+      # - name: stop testnet
+      #   run: |
+      #     cd ${{ github.workspace }}/polkadot-launch
+      #     pm2 stop measure-block-time-rococo-relay-for-${{ matrix.chain-spec.id }}
+      #     pm2 stop measure-block-time-${{ matrix.chain-spec.id }}
+      #     pm2 stop polkadot-launch
       # - if: always()
       #   uses: actions/upload-artifact@v2
       #   with:
-      #     name: block-time-${{ matrix.chain-spec.id }}.json
-      #     path: ${{ github.workspace }}/block-time-${{ matrix.chain-spec.id }}.json
-      - if: always()
-        name: test - rococo alice peered successfully
-        run: |
-          grep '💤 Idle (${{ matrix.chain-spec.expected.peer-count.relay }} peers)' ${{ github.workspace }}/polkadot-launch/alice.log
-      - if: always()
-        name: test - rococo alice imported block ${{ matrix.chain-spec.expected.block-count.relay }}
-        run: |
-          grep ' Imported #${{ matrix.chain-spec.expected.block-count.relay }} ' ${{ github.workspace }}/polkadot-launch/alice.log
-      - if: always()
-        name: test - calamari alice peered successfully
-        run: |
-          grep '\[Parachain\] 💤 Idle (${{ matrix.chain-spec.expected.peer-count.para }} peers)' ${{ github.workspace }}/polkadot-launch/9944.log
-      # Add the manta-pay, asset-manager and assets storage items and run stress test separately,
-      # in order to not break the logic of the other integration tests, which don't work with real data yet.
+      #     name: polkadot-launch-for-${{ matrix.chain-spec.id }}-stdout.log
+      #     path: ${{ github.workspace }}/polkadot-launch-for-${{ matrix.chain-spec.id }}-stdout.log
+      # - if: always()
+      #   uses: actions/upload-artifact@v2
+      #   with:
+      #     name: polkadot-launch-for-${{ matrix.chain-spec.id }}-stderr.log
+      #     path: ${{ github.workspace }}/polkadot-launch-for-${{ matrix.chain-spec.id }}-stderr.log
+      # - if: always()
+      #   uses: actions/upload-artifact@v2
+      #   with:
+      #     name: measure-block-time-rococo-relay-for-${{ matrix.chain-spec.id }}-stdout.log
+      #     path: ${{ github.workspace }}/measure-block-time-rococo-relay-for-${{ matrix.chain-spec.id }}-stdout.log
+      # - if: always()
+      #   uses: actions/upload-artifact@v2
+      #   with:
+      #     name: measure-block-time-rococo-relay-for-${{ matrix.chain-spec.id }}-stderr.log
+      #     path: ${{ github.workspace }}/measure-block-time-rococo-relay-for-${{ matrix.chain-spec.id }}-stderr.log
+      # - if: always()
+      #   uses: actions/upload-artifact@v2
+      #   with:
+      #     name: measure-block-time-${{ matrix.chain-spec.id }}-stdout.log
+      #     path: ${{ github.workspace }}/measure-block-time-${{ matrix.chain-spec.id }}-stdout.log
+      # - if: always()
+      #   uses: actions/upload-artifact@v2
+      #   with:
+      #     name: measure-block-time-${{ matrix.chain-spec.id }}-stderr.log
+      #     path: ${{ github.workspace }}/measure-block-time-${{ matrix.chain-spec.id }}-stderr.log
+      # - if: always()
+      #   uses: actions/upload-artifact@v2
+      #   with:
+      #     name: rococo-alice-relay-for-${{ matrix.chain-spec.id }}.log
+      #     path: ${{ github.workspace }}/polkadot-launch/alice.log
+      # - if: always()
+      #   uses: actions/upload-artifact@v2
+      #   with:
+      #     name: rococo-bob-relay-for-${{ matrix.chain-spec.id }}.log
+      #     path: ${{ github.workspace }}/polkadot-launch/bob.log
+      # - if: always()
+      #   uses: actions/upload-artifact@v2
+      #   with:
+      #     name: ${{ matrix.chain-spec.id }}-alice.log
+      #     path: ${{ github.workspace }}/polkadot-launch/9944.log
+      # - if: always()
+      #   uses: actions/upload-artifact@v2
+      #   with:
+      #     name: ${{ matrix.chain-spec.id }}-bob.log
+      #     path: ${{ github.workspace }}/polkadot-launch/9944.log
+      # - name: parse rococo block times
+      #   run: |
+      #     grep '#.*' ${{ github.workspace }}/measure-block-time-rococo-relay-for-${{ matrix.chain-spec.id }}-stdout.log | while read -r line; do words=($line); echo ${words[6]},${words[10]} | tee ${{ github.workspace }}/block-time-rococo.csv; done
+      #     if [ ! -f ${{ github.workspace }}/block-time-rococo.csv ]; then echo "block times not detected"; exit 1; fi
+      #     jq -s -R '[split("\n") | .[] | select(length > 0) | split(",") | {block:.[0]|tonumber, time:.[1]|tonumber} ]' ${{ github.workspace }}/block-time-rococo.csv > ${{ github.workspace }}/block-time-rococo.json
+      # - if: always()
+      #   uses: actions/upload-artifact@v2
+      #   with:
+      #     name: block-time-rococo-relay-for-${{ matrix.chain-spec.id }}.json
+      #     path: ${{ github.workspace }}/block-time-rococo.json
+      # # - if: always()
+      # # - name: parse calamari block times
+      # #   run: |
+      # #     grep '#.*' ${{ github.workspace }}/measure-block-time-${{ matrix.chain-spec.id }}-stdout.log | while read -r line; do words=($line); echo ${words[6]},${words[10]} | tee ${{ github.workspace }}/block-time-${{ matrix.chain-spec.id }}.csv; done
+      # #     if [ ! -f ${{ github.workspace }}/block-time-${{ matrix.chain-spec.id }}.csv ]; then echo "block times not detected"; exit 1; fi
+      # #     jq -s -R '[split("\n") | .[] | select(length > 0) | split(",") | {block:.[0]|tonumber, time:.[1]|tonumber} ]' ${{ github.workspace }}/block-time-${{ matrix.chain-spec.id }}.csv > ${{ github.workspace }}/block-time-${{ matrix.chain-spec.id }}.json
+      # # - if: always()
+      # #   uses: actions/upload-artifact@v2
+      # #   with:
+      # #     name: block-time-${{ matrix.chain-spec.id }}.json
+      # #     path: ${{ github.workspace }}/block-time-${{ matrix.chain-spec.id }}.json
+      # - if: always()
+      #   name: test - rococo alice peered successfully
+      #   run: |
+      #     grep '💤 Idle (${{ matrix.chain-spec.expected.peer-count.relay }} peers)' ${{ github.workspace }}/polkadot-launch/alice.log
+      # - if: always()
+      #   name: test - rococo alice imported block ${{ matrix.chain-spec.expected.block-count.relay }}
+      #   run: |
+      #     grep ' Imported #${{ matrix.chain-spec.expected.block-count.relay }} ' ${{ github.workspace }}/polkadot-launch/alice.log
+      # - if: always()
+      #   name: test - calamari alice peered successfully
+      #   run: |
+      #     grep '\[Parachain\] 💤 Idle (${{ matrix.chain-spec.expected.peer-count.para }} peers)' ${{ github.workspace }}/polkadot-launch/9944.log
+      # # Add the manta-pay, asset-manager and assets storage items and run stress test separately,
+      # # in order to not break the logic of the other integration tests, which don't work with real data yet.
       - name: append manta-pay storage
         run: |
           wget -P ${{ github.workspace }}/Manta/tests/data https://manta-ops.s3.amazonaws.com/integration-tests-data/storage.json
@@ -382,9 +382,10 @@ jobs:
             -- $HOME/.local/share/calamari-pc/${{ matrix.chain-spec.id }}-${GITHUB_SHA:0:7}-launch-config.json
       - name: run signer test server
         run: |
-          git clone manta-signer
-          cd signer
-          run signer-test-server
+          git clone https://github.com/Manta-Network/manta-signer.git
+          cd manta-signer
+          cargo install tauri-cli
+          cargo run --example test_server --features=unsafe-disable-cors,disable-restart --release
           cd ..
       - name: run full sync test
         run: |
