Change to dolphin without fi
Signed-off-by: Georgi Zlatarev <georgi.zlatarev@manta.network>

diff --git a/.github/workflows/publish_draft_releases.yml b/.github/workflows/publish_draft_releases.yml
--- a/.github/workflows/publish_draft_releases.yml
+++ b/.github/workflows/publish_draft_releases.yml
@@ -349,7 +349,7 @@ jobs:
       fail-fast: false
       matrix:
         chain-spec:
-          - id: calamari-local
+          - id: dolphin-dev
             expected:
               block-count:
                 relay: 25
@@ -357,7 +357,7 @@ jobs:
               peer-count:
                 relay: 5
                 para: 2
-          - id: calamari-dev
+          - id: dolphin-local
             expected:
               block-count:
                 relay: 25
@@ -499,10 +499,10 @@ jobs:
           yarn
           yarn correctness_test --address=ws://127.0.0.1:9921
           echo $?
-          if [ $? != 0 ]; then echo "Ledger RPC correctness test failed!"; exit 1; fi
+          if [ $? != 0 ]; then echo "Ledger RPC correctness test failed!"; exit 1;
           yarn performance_test --address=ws://127.0.0.1:9921
           echo $?
-          if [ $? != 0 ]; then echo "Ledger RPC performance test failed!"; exit 1; fi
+          if [ $? != 0 ]; then echo "Ledger RPC performance test failed!"; exit 1;
       - name: check if target block is finalized
         run: |
           cd ${{ github.workspace }}/dev-tools-calamari/check-finalized-block
