Parse runtime upgrade log

diff --git a/.github/workflows/publish-draft-releases.yml b/.github/workflows/publish-draft-releases.yml
--- a/.github/workflows/publish-draft-releases.yml
+++ b/.github/workflows/publish-draft-releases.yml
@@ -442,7 +442,11 @@ jobs:
         with:
           name: runtime-upgrade-test-for-${{ matrix.chain-spec.id }}-stderr.log
           path: ${{ github.workspace }}/test-runtime-upgrade-${{ matrix.chain-spec.id }}-stderr.log
-
+      -
+        name: parse runtime upgrade log
+        run: |
+          grep 'Upgrading from' ${{ github.workspace }}/test-runtime-upgrade-${{ matrix.chain-spec.id }}-stdout.log | while read -r line; do words=($line); echo ${words} | tee ${{ github.workspace }}/block-time-rococo.csv; done
+          if [ ! -f ${{ github.workspace }}/block-time-rococo.csv ]; then echo "Runtime upgrade failed"; exit 1; fi
   integration-test:
     needs:
       - build-node
