Add 120 sleep without fi
Signed-off-by: Georgi Zlatarev <georgi.zlatarev@manta.network>

diff --git a/.github/workflows/publish_draft_releases.yml b/.github/workflows/publish_draft_releases.yml
--- a/.github/workflows/publish_draft_releases.yml
+++ b/.github/workflows/publish_draft_releases.yml
@@ -497,12 +497,12 @@ jobs:
           cd ${{ github.workspace }}/Manta/tests
           yarn install
           yarn
-          yarn test --address=ws://127.0.0.1:9921
+          yarn correctness_test --address=ws://127.0.0.1:9921
           echo $?
-          if [ $? != 0 ]; then echo "Ledger RPC correctness test failed!"; exit 1; fi
+          if [ $? != 0 ]; then echo "Ledger RPC correctness test failed!"; exit 1;
           yarn performance_test --address=ws://127.0.0.1:9921
           echo $?
-          if [ $? != 0 ]; then echo "Ledger RPC performance test failed!"; exit 1; fi
+          if [ $? != 0 ]; then echo "Ledger RPC performance test failed!"; exit 1;
       - name: check if target block is finalized
         run: |
           cd ${{ github.workspace }}/dev-tools-calamari/check-finalized-block
