Try ledger-rpc unit test without fi
Signed-off-by: Georgi Zlatarev <georgi.zlatarev@manta.network>

diff --git a/.github/workflows/publish_draft_releases.yml b/.github/workflows/publish_draft_releases.yml
--- a/.github/workflows/publish_draft_releases.yml
+++ b/.github/workflows/publish_draft_releases.yml
@@ -497,6 +497,8 @@ jobs:
           yarn install
           yarn
           yarn test --address=ws://127.0.0.1:9921
+          echo $?
+          if [ $? != 0 ]; then echo "Ledger RPC test failed!"; exit 1;
           sleep 180
       - name: check if target block is finalized
         run: |
