Query finalized block instead of parsing logs in CI tests

diff --git a/.github/workflows/publish-draft-releases.yml b/.github/workflows/publish-draft-releases.yml
--- a/.github/workflows/publish-draft-releases.yml
+++ b/.github/workflows/publish-draft-releases.yml
@@ -747,9 +747,12 @@ jobs:
         run: |
           grep '\[Parachain\] 💤 Idle (${{ matrix.chain-spec.expected.peer-count.para }} peers)' ${{ github.workspace }}/manta-pc-launch/9921.log
       -
-        name: test - calamari alice finalized block ${{ matrix.chain-spec.expected.block-count.para }}
+        name: check if target block is finalized
         run: |
-          grep '\[Parachain\] .* finalized #${{ matrix.chain-spec.expected.block-count.para }} ' ${{ github.workspace }}/manta-pc-launch/9921.log
+          cd ${{ github.workspace }}/dev-tools/check-finalized-block
+          node index.js --address=ws://127.0.0.1:9921 --target_block=${{ matrix.chain-spec.expected.block-count.para }}
+          echo $?
+          if [ $? == 1 ]; then echo "Failed to finalize the target block - ${{ matrix.chain-spec.expected.block-count.para }}"; exit 1; fi
 
   build-changelog:
     runs-on: ubuntu-20.04
