[Manta] Integrate `v0.9.13` upstream changes (#294)

diff --git a/.github/workflows/publish-draft-releases.yml b/.github/workflows/publish-draft-releases.yml
--- a/.github/workflows/publish-draft-releases.yml
+++ b/.github/workflows/publish-draft-releases.yml
@@ -51,10 +51,8 @@ jobs:
         runtime:
           -
             name: calamari
-            para-id: 2084
           -
             name: manta
-            para-id: 2015
     steps:
       -
         uses: actions/checkout@v2
@@ -177,6 +175,12 @@ jobs:
         with:
           name: config-for-integration-test
           path: .github/resources/config-for-integration-test.json
+      -
+        name: upload
+        uses: actions/upload-artifact@v2
+        with:
+          name: config-for-runtime-upgrade-test
+          path: .github/resources/config-for-runtime-upgrade-test.json
 
   build-node-base:
     needs:
@@ -269,13 +273,6 @@ jobs:
         with:
           name: manta-base
           path: target/release/manta
-      -
-        if: ${{ needs.check-for-runtime-upgrade.outputs.do-versions-match == 'false' }}
-        name: upload
-        uses: actions/upload-artifact@v2
-        with:
-          name: config-for-runtime-upgrade-test
-          path: .github/resources/config-for-runtime-upgrade-test.json
 
   runtime-upgrade-test:
     needs:
@@ -293,17 +290,15 @@ jobs:
           -
             name: calamari
             chain-spec: calamari-testnet-ci
-            para-id: 2084
           -
             name: manta
             chain-spec: manta-testnet-ci
-            para-id: 2015
     steps:
       -
         if: ${{ needs.check-for-runtime-upgrade.outputs.do-versions-match == 'false' }}
         run: |
           ls -ahl ${{ github.workspace }}/
-          mkdir -p $HOME/.local/share/calamari-pc
+          mkdir -p $HOME/.local/share/${{ matrix.runtime.name }}-pc
           mkdir -p $HOME/.local/bin
           echo "${HOME}/.nvm/versions/node/v16.3.0/bin" >> $GITHUB_PATH
           echo "${HOME}/.local/bin" >> $GITHUB_PATH
@@ -326,29 +321,27 @@ jobs:
         if: ${{ needs.check-for-runtime-upgrade.outputs.do-versions-match == 'false' }}
         name: fetch and chmod polkadot
         run: |
-          curl -L -o $HOME/.local/bin/polkadot https://github.com/paritytech/polkadot/releases/download/v0.9.12/polkadot
+          curl -L -o $HOME/.local/bin/polkadot https://github.com/paritytech/polkadot/releases/download/v0.9.13/polkadot
           chmod +x $HOME/.local/bin/polkadot
           ls -ahl $HOME/.local/bin/
       -
         if: ${{ needs.check-for-runtime-upgrade.outputs.do-versions-match == 'false' }}
         id: create-chainspec
         run: |
-          manta-base build-spec --chain ${{ matrix.runtime.chain-spec }} --disable-default-bootnode --raw > $HOME/.local/share/calamari-pc/${{ matrix.runtime.chain-spec }}-spec.json
+          manta-base build-spec --chain ${{ matrix.runtime.chain-spec }} --disable-default-bootnode --raw > $HOME/.local/share/${{ matrix.runtime.name }}-pc/${{ matrix.runtime.chain-spec }}-spec.json
           jq \
             --sort-keys \
-            --arg name "calamari testnet base" \
+            --arg name "${{ matrix.runtime.name }} testnet base" \
             --arg id ${{ matrix.runtime.chain-spec }}-base \
             --arg relay_chain rococo-local-base \
-            --arg parachain_id 2084 \
             '. |
               .name = $name |
               .id = $id |
               .relay_chain = $relay_chain |
-              .para_id = ($parachain_id | tonumber) |
               .telemetryEndpoints = [["/dns/api.telemetry.manta.systems/tcp/443/x-parity-wss/%2Fsubmit%2F", 0]]
-            ' $HOME/.local/share/calamari-pc/${{ matrix.runtime.chain-spec }}-spec.json > $HOME/.local/share/calamari-pc/${{ matrix.runtime.chain-spec }}-base-spec.json
-          ls -ahl $HOME/.local/share/calamari-pc/
-          manta-base export-state --chain $HOME/.local/share/calamari-pc/${{ matrix.runtime.chain-spec }}-base-spec.json > $HOME/.local/share/calamari-pc/${{ matrix.runtime.chain-spec }}-state.json || true
+            ' $HOME/.local/share/${{ matrix.runtime.name }}-pc/${{ matrix.runtime.chain-spec }}-spec.json > $HOME/.local/share/${{ matrix.runtime.name }}-pc/${{ matrix.runtime.chain-spec }}-base-spec.json
+          ls -ahl $HOME/.local/share/${{ matrix.runtime.name }}-pc/
+          manta-base export-state --chain $HOME/.local/share/${{ matrix.runtime.name }}-pc/${{ matrix.runtime.chain-spec }}-base-spec.json > $HOME/.local/share/${{ matrix.runtime.name }}-pc/${{ matrix.runtime.chain-spec }}-state.json || true
       -
         if: ${{ needs.check-for-runtime-upgrade.outputs.do-versions-match == 'false' }}
         name: fetch config-for-runtime-upgrade-test
@@ -366,16 +359,16 @@ jobs:
             --arg relaychain_id rococo-local-base \
             --arg relaychain_name "rococo local base" \
             --arg parachains_bin $HOME/.local/bin/manta-base \
-            --arg parachains_spec $HOME/.local/share/calamari-pc/${{ matrix.runtime.chain-spec }}-base-spec.json \
+            --arg parachains_spec $HOME/.local/share/${{ matrix.runtime.name }}-pc/${{ matrix.runtime.chain-spec }}-base-spec.json \
             '.
               | .relaychain.bin = $relaychain_bin
               | .relaychain.mutation.id = $relaychain_id
               | .relaychain.mutation.name = $relaychain_name
               | .parachains[].bin = $parachains_bin
               | .parachains[].chain = $parachains_spec
-            ' > $HOME/.local/share/calamari-pc/${{ matrix.runtime.chain-spec }}-base-launch-config.json
-          jq . $HOME/.local/share/calamari-pc/${{ matrix.runtime.chain-spec }}-base-launch-config.json
-          ls -ahl $HOME/.local/share/calamari-pc/
+            ' > $HOME/.local/share/${{ matrix.runtime.name }}-pc/${{ matrix.runtime.chain-spec }}-base-launch-config.json
+          jq . $HOME/.local/share/${{ matrix.runtime.name }}-pc/${{ matrix.runtime.chain-spec }}-base-launch-config.json
+          ls -ahl $HOME/.local/share/${{ matrix.runtime.name }}-pc/
       -
         if: ${{ needs.check-for-runtime-upgrade.outputs.do-versions-match == 'false' }}
         uses: actions/checkout@v2
@@ -387,7 +380,7 @@ jobs:
         uses: actions/checkout@v2
         with:
           repository: Manta-Network/Dev-Tools
-          path: dev-tools-calamari
+          path: dev-tools
       -
         if: ${{ needs.check-for-runtime-upgrade.outputs.do-versions-match == 'false' }}
         name: launch testnet
@@ -400,12 +393,12 @@ jobs:
             --output ${{ github.workspace }}/manta-pc-launch-for-${{ matrix.runtime.chain-spec }}-stdout.log \
             --error ${{ github.workspace }}/manta-pc-launch-for-${{ matrix.runtime.chain-spec }}-stderr.log \
             --no-autorestart \
-            -- $HOME/.local/share/calamari-pc/${{ matrix.runtime.chain-spec }}-base-launch-config.json
+            -- $HOME/.local/share/${{ matrix.runtime.name }}-pc/${{ matrix.runtime.chain-spec }}-base-launch-config.json
       -
         if: ${{ needs.check-for-runtime-upgrade.outputs.do-versions-match == 'false' }}
-        name: init measure-block-time calamari
+        name: init measure-block-time ${{ matrix.runtime.name }}
         run: |
-          cd ${{ github.workspace }}/dev-tools-calamari/measure-block-time
+          cd ${{ github.workspace }}/dev-tools/measure-block-time
           yarn install
           pm2 start index.js \
             --name measure-block-time-${{ matrix.runtime.chain-spec }} \
@@ -416,27 +409,27 @@ jobs:
             --address=ws://127.0.0.1:9921
       -
         if: ${{ needs.check-for-runtime-upgrade.outputs.do-versions-match == 'false' }}
-        name: fetch new calamari_runtime.compact.compressed.wasm
+        name: fetch new ${{ matrix.runtime.name }}_runtime.compact.compressed.wasm
         uses: actions/download-artifact@v2
         with:
-          name: calamari-runtime
+          name: ${{ matrix.runtime.name }}-runtime
       -
         if: ${{ needs.check-for-runtime-upgrade.outputs.do-versions-match == 'false' }}
         name: run test suites
         run: |
           # todo: implement moonbeam-like js test suite triggers here
           sleep 120
-          echo "midnight supply never you faith veteran danger purity tired illness dune token" > ${{ github.workspace }}/dev-tools-calamari/runtime-upgrade-test/root_mnemonics
+          echo "midnight supply never you faith veteran danger purity tired illness dune token" > ${{ github.workspace }}/dev-tools/runtime-upgrade-test/root_mnemonics
           curl -vH 'Content-Type: application/json' --data '{ "jsonrpc":"2.0", "method":"author_insertKey", "params":["aura", "inhale connect winner reduce cheese bachelor crucial never metal seat time wage", "0xee73f78b7dd29f30902c1a3bd1e4a6fcc2f26be088343d3ee011e2660fd02a66"],"id":1 }' localhost:9971
           curl -vH 'Content-Type: application/json' --data '{ "jsonrpc":"2.0", "method":"author_insertKey", "params":["aura", "timber else work trophy build winner mechanic chunk budget orchard glide extra", "0x7cd4af9ad51d443740f71ecd5850385e98985224628c5ea08209bb2015523f3c"],"id":1 }' localhost:9972
           curl -vH 'Content-Type: application/json' --data '{ "jsonrpc":"2.0", "method":"author_insertKey", "params":["aura", "civil cigar remain hybrid glove symptom review what pole lock concert lamp", "0xb40aa6bd104d0260b60350c2fb30d4882437466d66135130b667799ea6c9f52b"],"id":1 }' localhost:9973
           curl -vH 'Content-Type: application/json' --data '{ "jsonrpc":"2.0", "method":"author_insertKey", "params":["aura", "output evidence anger invest country opinion girl mouse direct double carbon usage", "0x4a3aa51469e802be6504422cd9dd03be638ac3f6dc3a7c0c85a6ace3e72f0048"],"id":1 }' localhost:9974
           curl -vH 'Content-Type: application/json' --data '{ "jsonrpc":"2.0", "method":"author_insertKey", "params":["aura", "series disorder today argue interest pond flight guess asthma guilt road gadget", "0xa68feb4fe2ea3f8ff288af4254aad2284e1cd0da67cb9ea61c13632bad57eb40"],"id":1 }' localhost:9975
-          cp calamari_runtime.compact.compressed.wasm ${{ github.workspace }}/dev-tools-calamari/runtime-upgrade-test/calamari.wasm
-          cd ${{ github.workspace }}/dev-tools-calamari/runtime-upgrade-test
+          cp ${{ matrix.runtime.name }}_runtime.compact.compressed.wasm ${{ github.workspace }}/dev-tools/runtime-upgrade-test/calamari.wasm
+          cd ${{ github.workspace }}/dev-tools/runtime-upgrade-test
           yarn install
           yarn
-          sleep 60
+          sleep 120
           pm2 start index.js \
             --name test-runtime-upgrade-${{ matrix.runtime.chain-spec }} \
             --output ${{ github.workspace }}/test-runtime-upgrade-${{ matrix.runtime.chain-spec }}-stdout.log \
@@ -452,10 +445,10 @@ jobs:
         if: ${{ needs.check-for-runtime-upgrade.outputs.do-versions-match == 'false' }}
         name: check if spec version was successfully incremented
         run: |
-          cd ${{ github.workspace }}/dev-tools-calamari/runtime-upgrade-test
-          node check_runtime_version.js --address=ws://127.0.0.1:9921 --compare_to={{ needs.parse-runtimes.outputs.calamari-runtime-base }}
+          cd ${{ github.workspace }}/dev-tools/runtime-upgrade-test
+          node check_runtime_version.js --address=ws://127.0.0.1:9921 --compare_to=${{ needs.parse-runtimes.outputs.calamari-runtime-base }}
           echo $?
-          if [ $? == 0 ]; then echo "Runtime upgrade failed, still using old spec version - ${{ needs.parse-runtimes.outputs.calamari-runtime-base }}"; exit 1; fi
+          if [ $? == 1 ]; then echo "Runtime upgrade failed, still using old spec version - ${{ needs.parse-runtimes.outputs.calamari-runtime-base }}"; exit 1; fi
           cd ${{ github.workspace }}
       -
         if: ${{ needs.check-for-runtime-upgrade.outputs.do-versions-match == 'false' }}
@@ -479,7 +472,7 @@ jobs:
           path: ${{ github.workspace }}/test-runtime-upgrade-${{ matrix.runtime.chain-spec }}-stderr.log
       -
         if: ${{ needs.check-for-runtime-upgrade.outputs.do-versions-match == 'false' }}
-        name: parse calamari block times
+        name: parse ${{ matrix.runtime.name }} block times
         run: |
           grep '#.*' ${{ github.workspace }}/measure-block-time-${{ matrix.runtime.chain-spec }}-stdout.log | while read -r line; do words=($line); echo ${words[6]},${words[10]} | tee ${{ github.workspace }}/block-time-${{ matrix.runtime.chain-spec }}.csv; done
           if [ ! -f ${{ github.workspace }}/block-time-${{ matrix.runtime.chain-spec }}.csv ]; then echo "block times not detected"; exit 1; fi
@@ -537,7 +530,7 @@ jobs:
       -
         name: fetch and chmod polkadot
         run: |
-          curl -L -o $HOME/.local/bin/polkadot https://github.com/paritytech/polkadot/releases/download/v0.9.12/polkadot
+          curl -L -o $HOME/.local/bin/polkadot https://github.com/paritytech/polkadot/releases/download/v0.9.13/polkadot
           chmod +x $HOME/.local/bin/polkadot
           ls -ahl $HOME/.local/bin/
       -
@@ -549,12 +542,10 @@ jobs:
             --arg name "calamari testnet ${GITHUB_SHA:0:7}" \
             --arg id ${{ matrix.chain-spec.id }}-${GITHUB_SHA:0:7} \
             --arg relay_chain rococo-local-${GITHUB_SHA:0:7} \
-            --arg parachain_id 2084 \
             '. |
               .name = $name |
               .id = $id |
               .relay_chain = $relay_chain |
-              .para_id = ($parachain_id | tonumber) |
               .telemetryEndpoints = [["/dns/api.telemetry.manta.systems/tcp/443/x-parity-wss/%2Fsubmit%2F", 0]]
             ' $HOME/.local/share/calamari-pc/${{ matrix.chain-spec.id }}-spec.json > $HOME/.local/share/calamari-pc/${{ matrix.chain-spec.id }}-${GITHUB_SHA:0:7}-spec.json
           ls -ahl $HOME/.local/share/calamari-pc/
@@ -659,7 +650,7 @@ jobs:
         name: run test suites
         run: |
           # todo: implement moonbeam-like js test suite triggers here
-          sleep 210
+          sleep 300
       -
         name: stop testnet
         run: |
@@ -768,10 +759,8 @@ jobs:
         runtime:
           -
             name: calamari
-            para-id: 2084
           -
             name: manta
-            para-id: 2015
     if: startsWith(github.ref, 'refs/tags')
     steps:
       -
@@ -848,10 +837,8 @@ jobs:
         runtime:
           -
             name: calamari
-            para-id: 2084
           -
             name: manta
-            para-id: 2015
     if: startsWith(github.ref, 'refs/tags')
     steps:
       -
@@ -1254,6 +1241,7 @@ jobs:
         name: run docker image
         run: |
           sudo docker run -d ${{ matrix.runtime.name }} > docker_id.log
+          sleep 30
       -
         name: check syncing
         run: |
