Add 120 sleep with fi
Signed-off-by: Georgi Zlatarev <georgi.zlatarev@manta.network>

diff --git a/.github/workflows/publish_draft_releases.yml b/.github/workflows/publish_draft_releases.yml
--- a/.github/workflows/publish_draft_releases.yml
+++ b/.github/workflows/publish_draft_releases.yml
@@ -499,10 +499,10 @@ jobs:
           yarn
           yarn test --address=ws://127.0.0.1:9921
           echo $?
-          if [ $? != 0 ]; then echo "Ledger RPC correctness test failed!"; exit 1;
+          if [ $? != 0 ]; then echo "Ledger RPC correctness test failed!"; exit 1; fi
           yarn performance_test --address=ws://127.0.0.1:9921
           echo $?
-          if [ $? != 0 ]; then echo "Ledger RPC performance test failed!"; exit 1;
+          if [ $? != 0 ]; then echo "Ledger RPC performance test failed!"; exit 1; fi
       - name: check if target block is finalized
         run: |
           cd ${{ github.workspace }}/dev-tools-calamari/check-finalized-block
