Check new parsing of runtime upgrade test

diff --git a/.github/workflows/publish-draft-releases.yml b/.github/workflows/publish-draft-releases.yml
--- a/.github/workflows/publish-draft-releases.yml
+++ b/.github/workflows/publish-draft-releases.yml
@@ -441,7 +441,20 @@ jobs:
             --error ${{ github.workspace }}/test-runtime-upgrade-${{ matrix.runtime.chain-spec }}-stderr.log \
             --no-autorestart
           cd ${{ github.workspace }}
-          sleep 120
+          sleep 180
+      -
+        # check_runtime_version.js reads the spec-version on-chain
+        # and compares it to the old runtime version we parsed earlier
+        # returns 0 if the former is lass than or equal to the latter
+        # otherwise returns 1
+        if: ${{ needs.check-for-runtime-upgrade.outputs.do-versions-match == 'false' }}
+        name: check if spec version was successfully incremented
+        run: |
+          cd ${{ github.workspace }}/dev-tools-calamari/runtime-upgrade-test
+          node check_runtime_version.js --address=ws://127.0.0.1:9921 --compare_to={{ needs.check-for-runtime-upgrade.outputs.old_version }}
+          echo $?
+          if [ $? == 0 ]; then echo "Runtime upgrade failed, spec version failed to increment..."; exit 1; fi
+          cd ${{ github.workspace }}
       -
         if: ${{ needs.check-for-runtime-upgrade.outputs.do-versions-match == 'false' }}
         name: stop testnet
@@ -464,25 +477,11 @@ jobs:
           path: ${{ github.workspace }}/test-runtime-upgrade-${{ matrix.runtime.chain-spec }}-stderr.log
       -
         if: ${{ needs.check-for-runtime-upgrade.outputs.do-versions-match == 'false' }}
-        name: parse runtime upgrade log
-        run: |
-          grep 'Included at block hash' ${{ github.workspace }}/test-runtime-upgrade-${{ matrix.runtime.chain-spec }}-stdout.log | while read -r line; do words=($line); echo ${words} | tee ${{ github.workspace }}/runtime-upgrade-output.csv; done
-          if [ ! -f ${{ github.workspace }}/runtime-upgrade-output.csv ]; then echo "Runtime upgrade failed"; exit 1; fi
-      -
-        if: ${{ needs.check-for-runtime-upgrade.outputs.do-versions-match == 'false' }}
         name: parse calamari block times
         run: |
           grep '#.*' ${{ github.workspace }}/measure-block-time-${{ matrix.runtime.chain-spec }}-stdout.log | while read -r line; do words=($line); echo ${words[6]},${words[10]} | tee ${{ github.workspace }}/block-time-${{ matrix.runtime.chain-spec }}.csv; done
           if [ ! -f ${{ github.workspace }}/block-time-${{ matrix.runtime.chain-spec }}.csv ]; then echo "block times not detected"; exit 1; fi
           jq -s -R '[split("\n") | .[] | select(length > 0) | split(",") | {block:.[0]|tonumber, time:.[1]|tonumber} ]' ${{ github.workspace }}/block-time-${{ matrix.runtime.chain-spec }}.csv > ${{ github.workspace }}/block-time-${{ matrix.runtime.chain-spec }}.json
-      -
-        if: ${{ needs.check-for-runtime-upgrade.outputs.do-versions-match == 'false' }}
-        name: check if spec version was incremented
-        run: |
-          sleep 60
-          node check_runtime_version.js --compare_to={{ needs.check-for-runtime-upgrade.outputs.old_version }}
-          echo $?
-          if [ ${ $? } == 0 ]; then echo "Runtime upgrade failed, spec_version was not incremented..."; exit 1; fi
 
   integration-test:
     needs:
