Add the docker image test as a job in the publish-draft-release which uses local image

diff --git a/.github/workflows/publish-draft-releases.yml b/.github/workflows/publish-draft-releases.yml
--- a/.github/workflows/publish-draft-releases.yml
+++ b/.github/workflows/publish-draft-releases.yml
@@ -807,6 +807,7 @@ jobs:
       - integration-test
       # a work around of rococo bug
       # - runtime-upgrade-test
+      - docker-image-test
     outputs:
       release_url: ${{ steps.create-release.outputs.html_url }}
       asset_upload_url: ${{ steps.create-release.outputs.upload_url }}
@@ -1168,5 +1169,104 @@ jobs:
           echo "::set-output name=match::false"
           if [[ ${{ steps.get-runtime-version-base.outputs.runtime-ver-base }} == ${{ steps.get-runtime-version-current.outputs.runtime-ver-current }} ]]; then echo "::set-output name=match::true"
           fi
+
+  start-docker-image-tester:
+    runs-on: ubuntu-20.04
+    outputs:
+      runner-label: ${{ steps.start-self-hosted-runner.outputs.runner-label }}
+      aws-region: ${{ steps.start-self-hosted-runner.outputs.aws-region }}
+      aws-instance-id: ${{ steps.start-self-hosted-runner.outputs.aws-instance-id }}
+    steps:
+      -
+        id: start-self-hosted-runner
+        uses: audacious-network/aws-github-runner@v1.0.33
+        with:
+          mode: start
+          github-token: ${{ secrets.GH_SHR_TOKEN }}
+          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
+          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
+          aws-instance-ssh-public-key: ${{ env.AWS_INSTANCE_SSH_PUBLIC_KEY }}
+          aws-region: ${{ env.AWS_REGION }}
+          aws-subnet-id: ${{ env.AWS_SUBNET_ID }}
+          aws-security-group-id: ${{ env.AWS_SECURITY_GROUP_ID }}
+          aws-instance-type: ${{ env.AWS_INSTANCE_TYPE }}  # 32 vcpu, 64gb ram, $1.392 hourly
+          aws-instance-root-volume-size: 64
+          aws-image-search-pattern: ${{ env.AWS_IMAGE_SEARCH_PATTERN }}
+          aws-image-search-owners: ${{ env.AWS_IMAGE_SEARCH_OWNERS }}  # canonical
+
+  docker-image-test:
+    needs:
+      - build-node-current
+      - start-docker-image-tester
+    runs-on: ubuntu-20.04
+    steps:
+      -
+        name: setup directories
+        run: |
+          mkdir -p $HOME/.local/share/manta
+          mkdir -p $HOME/.local/bin
+          echo "${HOME}/.nvm/versions/node/v16.3.0/bin" >> $GITHUB_PATH
+          echo "${HOME}/.local/bin" >> $GITHUB_PATH
+      -
+        name: fetch manta
+        uses: actions/download-artifact@v2
+        with:
+          name: manta
+      -
+        uses: actions/checkout@v2
+      -
+        name: build docker image
+        run: |
+          cd docker/
+          mv ${{ github.workspace }}/manta manta
+          chmod +x manta
+          GIT_TAG=${{ github.event.release.tag_name }}
+          BINARY_NAME=manta
+          ln -s calamari.Dockerfile Dockerfile
+          docker build \
+            --build-arg PARA_BINARY_REF=${GIT_TAG} \
+            --build-arg PARA_BINARY_URL=manta \
+            --tag calamari   ./
+      -
+        name: run docker image
+        run: |
+          sudo docker run -d calamari > docker_id.log
+      -
+        name: check syncing
+        run: |
+          echo "Get the docker container ID:"
+          image_id=`cat docker_id.log`
+          echo $image_id
+          echo "Adjusting permissions so we can access docker logs..."
+          sudo chmod -R +x /var/lib/docker/
+          sudo cat /var/lib/docker/containers/${image_id}/${image_id}-json.log > docker_output.log
+          echo "Parsing the first best blocks emitted from the relaychain and parachain..."
+          grep 'best: #.*' docker_output.log | head -n 2 | while read -r line; do words=($line); echo ${words[9]:1} >> relay_output.txt; done
+          echo "Fail if there is no result..."
+          if [ ! -f relay_output.txt ]; then echo "sync not detected"; exit 1; fi
+          cat relay_output.txt
+          echo "Fail if any one of the blocks is equal to zero..."
+          nums=( $(cat relay_output.txt) )
+          if [ ${nums[0]} == 0 ]; then echo "sync not detected"; exit 1; fi
+          if [ ${nums[1]} == 0 ]; then echo "sync not detected"; exit 1; fi
+          echo "All good!"
+
+  stop-docker-image-tester:
+    needs:
+      - start-docker-image-tester
+      - docker-image-test
+    runs-on: ubuntu-20.04
+    if: ${{ always() }}
+    steps:
+      -
+        uses: audacious-network/aws-github-runner@v1.0.33
+        with:
+          mode: stop
+          github-token: ${{ secrets.GH_SHR_TOKEN }}
+          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
+          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
+          aws-region: ${{ needs.start-docker-image-tester.outputs.aws-region }}
+          runner-label: ${{ needs.start-docker-image-tester.outputs.runner-label }}
+          aws-instance-id: ${{ needs.start-docker-image-tester.outputs.aws-instance-id }}
 
 # yamllint enable rule:line-length
